'use strict';
const $=id=>document.getElementById(id);
let token='',config=null,keyState={},currentRun=null,eventSource=null,chatRunId=null,chatTaskId=null,chatEventSource=null,chatStreaming=null,chatTaskState=null,memberSequence=0;
const labels={queued:'等待中',running:'正在执行',completed:'已完成',failed:'失败',cancelled:'已停止',interrupted:'可恢复'};
const node=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
function notice(text,error=false){$('notice').hidden=false;$('notice').textContent=text;$('notice').className=error?'error':'';}
async function api(path,body,method,extraHeaders={}){const r=await fetch('/api'+path,{method:method||(body?'POST':'GET'),headers:{'content-type':'application/json','x-peachsh-token':token,...extraHeaders},...(body?{body:JSON.stringify(body)}:{})});let v;try{v=await r.json();}catch{throw Error('服务没有返回有效响应，请检查是否正在运行');}if(!r.ok)throw Error(v.error||`请求失败 ${r.status}`);return v;}
async function action(button,fn){if(button.disabled)return;button.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{button.disabled=false;}}
function show(view){for(const n of document.querySelectorAll('.view'))n.hidden=n.id!==view;for(const n of document.querySelectorAll('nav button'))n.classList.toggle('selected',n.dataset.view===view);$('page-title').textContent={chat:'对话',work:'工作台',models:'模型与 Key',account:'账户与余额'}[view];}
for(const n of document.querySelectorAll('nav button'))n.onclick=()=>show(n.dataset.view);
function renderChatRoutes(){if(!$('chat-route')||!config)return;const select=$('chat-route'),previous=select.value;select.replaceChildren();for(const r of config.routes){const option=node('option',`${r.name} · ${r.model}${keyState[r.id]?'':'（未配置 Key）'}`);option.value=r.id;option.disabled=!keyState[r.id];select.append(option);}if([...select.options].some(o=>o.value===previous&&!o.disabled))select.value=previous;else{const first=[...select.options].find(o=>!o.disabled);if(first)select.value=first.value;}}
function chatBubble(role,text){const bubble=node('div',undefined,`chat-bubble ${role}`);bubble.append(node('span',role==='user'?'你':'模型','chat-speaker'),node('div',text));return bubble;}
function renderChatTask(task){const box=$('chat-messages');if(!box)return;if(task)chatTaskState=task;const current=task||chatTaskState;box.replaceChildren();const messages=current?.messages?.filter(m=>(m.role==='user'||m.role==='assistant')&&typeof m.content==='string'&&m.content.trim())||[];if(!messages.length)box.append(node('div','模型正在准备回复…','empty'));for(const message of messages)box.append(chatBubble(message.role,message.content));if(current?.error){box.append(node('p',`任务失败：${current.error}`,'chat-error'));}if(chatStreaming!==null){box.append(chatBubble('assistant',chatStreaming||'模型正在回复…'));box.lastElementChild.classList.add('streaming');}const busy=['queued','running'].includes(current?.status);$('chat-status').textContent=current?.status?labels[current.status]||current.status:'';$('chat-stop').hidden=!busy;$('chat-send').disabled=busy;box.scrollTop=box.scrollHeight;}
async function loadChatTask(){if(!chatRunId)return;const run=await api(`/runs/${chatRunId}`),task=run.tasks.find(t=>t.id===chatTaskId);if(task){if($('chat-route')&&task.route?.id)$('chat-route').value=task.route.id;if(!['queued','running'].includes(task.status))chatStreaming=null;renderChatTask(task);}}
function connectChatEvents(){if(!chatRunId)return;chatEventSource?.close();const id=chatRunId;chatEventSource=new EventSource(`/api/runs/${id}/events`);chatEventSource.addEventListener('delta',e=>{const v=JSON.parse(e.data);if(v.task_id!==chatTaskId)return;chatStreaming=(chatStreaming||'')+v.data.text;renderChatTask(null);});chatEventSource.addEventListener('status',async e=>{const v=JSON.parse(e.data);if(v.task_id!==chatTaskId)return;if(['queued','running'].includes(v.data.status)){renderChatTask(null);return;}try{await loadChatTask();}catch(error){notice(error.message,true);}});}
function newChat(){chatEventSource?.close();chatEventSource=null;chatRunId=null;chatTaskId=null;chatTaskState=null;chatStreaming=null;if($('chat-messages'))$('chat-messages').replaceChildren(node('div','选择模型后发送第一条消息。','empty'));if($('chat-input'))$('chat-input').value='';$('chat-status').textContent='';$('chat-stop').hidden=true;$('chat-send').disabled=false;show('chat');}
async function openChatRun(id){chatEventSource?.close();const run=await api(`/runs/${id}`);if(run.kind!=='chat'||!run.tasks?.length)return openRun(id);const task=run.tasks[0];chatRunId=id;chatTaskId=task.id;chatStreaming=null;await loadChatTask();connectChatEvents();show('chat');}
async function openHistoryRun(id){const run=await api(`/runs/${id}`);if(run.kind==='chat')return openChatRun(id);return openRun(id);}
async function sendChat(){const input=$('chat-input'),message=input.value.trim();if(!message)throw Error('请输入消息');const route=$('chat-route').value;if(!route)throw Error('请先在模型与 Key中配置可用路由');const tools=$('chat-tools').checked,allowWrites=$('chat-writes').checked,allowCommands=$('chat-commands').checked;input.value='';chatStreaming='';try{if(!chatTaskId){const run=await api('/runs',{kind:'chat',title:message.slice(0,80),tasks:[{name:'chat-session',role:'对话助手',route_id:route,prompt:message,depends_on:[],write_scopes:allowWrites?['*']:[],tools,allow_commands:allowCommands,max_rounds:12}]},'POST',{'Idempotency-Key':crypto.randomUUID()});chatRunId=run.id;chatTaskId=run.tasks[0].id;}else{await api(`/tasks/${chatTaskId}/resume`,{message});}await loadChatTask();connectChatEvents();show('chat');}catch(error){input.value=message;chatStreaming=null;renderChatTask(null);throw error;}}
$('new-chat').onclick=newChat;$('chat-send').onclick=()=>action($('chat-send'),sendChat);$('chat-stop').onclick=()=>action($('chat-stop'),async()=>{if(chatTaskId){await api(`/tasks/${chatTaskId}/cancel`,{});notice('已请求停止当前对话。');}});$('chat-input').addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();$('chat-send').click();}});
$('chat-writes').onchange=e=>{if(e.target.checked)$('chat-tools').checked=true;};$('chat-commands').onchange=e=>{if(e.target.checked)$('chat-tools').checked=true;};
function field(label,value,type='text'){const l=node('label',label);const i=node('input');i.type=type;i.value=value??'';l.append(i);return [l,i];}
function addMember(){const index=++memberSequence;const box=node('div',undefined,'member');box.innerHTML='<div class="member-head"><span></span><button class="secondary" type="button">移除</button></div><div class="member-grid"></div><label>具体任务<textarea class="prompt" placeholder="说明目标、上下文和验收要求…"></textarea></label><label>前置成员（可选，用逗号分隔）<input class="dependencies" placeholder="例如：planner；等待完成后自动接收结果"></label><div class="member-options"><label class="check"><input type="checkbox" class="tools">启用项目文件工具</label><label class="check"><input type="checkbox" class="commands">允许命令执行（可访问本机；需单独运行）</label></div><label>可写入范围（留空只读，用逗号分隔）<input class="scopes" placeholder="例如：src/api, tests/api"></label>';
box.querySelector('.member-head span').textContent=`MEMBER ${String(index).padStart(2,'0')}`;box.querySelector('button').onclick=()=>{if($('members').children.length>1)box.remove();};
const [nl,ni]=field('成员名称',index===1?'lead':`worker-${index}`);ni.className='member-name';const [rl,ri]=field('职责',index===1?'开发负责人':'开发成员');ri.className='role';const ml=node('label','模型路由');const select=node('select');select.className='route';for(const r of config.routes){const o=node('option',`${r.name} · ${r.model}${keyState[r.id]?'':'（未配置 Key）'}`);o.value=r.id;select.append(o);}const preferred=config.routes.find(r=>keyState[r.id]&&r.id.startsWith('peachsh'))||config.routes.find(r=>keyState[r.id]);if(preferred)select.value=preferred.id;ml.append(select);box.querySelector('.member-grid').append(nl,rl,ml);box.querySelector('.commands').onchange=e=>{if(e.target.checked)box.querySelector('.tools').checked=true;};$('members').append(box);}
function newRun(){currentRun=null; memberSequence=0; $('run-title').value='';$('members').replaceChildren();addMember();eventSource?.close();$('run-panel').hidden=true;$('create-panel').hidden=false;show('work');}
$('new-run').onclick=newRun;$('add-member').onclick=addMember;
$('start-run').onclick=()=>action($('start-run'),async()=>{const tasks=[...$('members').children].map(b=>({name:b.querySelector('.member-name').value.trim(),role:b.querySelector('.role').value.trim(),route_id:b.querySelector('.route').value,prompt:b.querySelector('.prompt').value,depends_on:b.querySelector('.dependencies').value.split(',').map(s=>s.trim()).filter(Boolean),tools:b.querySelector('.tools').checked,allow_commands:b.querySelector('.commands').checked,write_scopes:b.querySelector('.scopes').value.split(',').map(s=>s.trim()).filter(Boolean),max_rounds:12}));if(tasks.length>1&&$('summarize').checked){if(tasks.some(t=>t.name==='team-summary'))throw Error('team-summary 是自动汇总成员的保留名称');tasks.push({name:'team-summary',role:'汇总与验收',route_id:tasks[0].route_id,prompt:'汇总前置成员的工作、验证证据、未解决问题和建议。区分已验证的结果与成员陈述，不要声称自己执行了测试。',depends_on:tasks.map(t=>t.name),write_scopes:[],tools:false,allow_commands:false,max_rounds:1});}const run=await api('/runs',{title:$('run-title').value.trim()||tasks[0].prompt.slice(0,50),tasks});await openRun(run.id);await history();});
async function history(){const runs=await api('/runs');$('history').replaceChildren();if(!runs.length)$('history').append(node('div','还没有任务，从右边开始吧。','empty'));for(const r of runs){const b=node('button',r.title);b.title=r.title;b.classList.toggle('active',r.id===currentRun||r.id===chatRunId);b.onclick=()=>action(b,()=>openHistoryRun(r.id));$('history').append(b);}}
function renderTask(task){const card=node('article',undefined,'card');card.dataset.task=task.id;const head=node('div',undefined,'task-head');const identity=node('div');identity.append(node('h2',task.spec.name),node('div',`${task.spec.role} · ${task.route.name} · ${task.route.model}`,'task-role'));head.append(identity,node('span',labels[task.status]||task.status,`pill ${task.status}`));const output=node('pre',task.output||'等待模型返回…','output');const err=node('p',task.error||'','task-error');const log=node('details');log.append(node('summary','工具与执行记录'));const lines=node('div','','tool-log');log.append(lines);const actions=node('div',undefined,'task-actions');const running=['running','queued'].includes(task.status);if(running){const stop=node('button','停止','danger');stop.onclick=()=>action(stop,async()=>{await api(`/tasks/${task.id}/cancel`,{});notice('已请求停止任务；正在执行的命令会在结束或超时后停止。');});actions.append(stop);}else{const input=node('input');input.placeholder='继续这个成员，保留身份、模型与上下文…';input.setAttribute('aria-label',`继续 ${task.spec.name}`);const send=node('button','继续任务 ↗','primary');send.onclick=()=>action(send,async()=>{await api(`/tasks/${task.id}/resume`,{message:input.value});await openRun(task.run_id);});actions.append(input,send);if(task.spec.write_scopes?.length){const review=node('button','查看变更','secondary');review.onclick=()=>action(review,async()=>{const r=await api(`/tasks/${task.id}/changes`);const lines=r.changes.map(c=>`${c.path} · ${c.kind} · 当前 ${c.current} · 写入 ${c.state} · 恢复 ${c.restore_state} · ${c.restorable?'可恢复':'不可恢复'}`).join('\\n');notice(lines||'没有记录到文件变更。');});const restore=node('button','恢复文件修改','secondary');restore.onclick=()=>action(restore,async()=>{const r=await api(`/tasks/${task.id}/restore`,{});if(r.ok&&r.status==='complete')notice(`已恢复 ${r.restored} 个文件；请重新检查工作区。`);await openRun(task.run_id);});actions.append(review,restore);}}card.append(head,output,err,log,actions);return card;}
async function openRun(id){eventSource?.close();currentRun=id;const run=await api(`/runs/${id}`);$('create-panel').hidden=true;$('run-panel').hidden=false;$('run-heading').textContent=run.title;$('task-results').replaceChildren(...run.tasks.map(renderTask));show('work');
// Replay durable events to rebuild tool logs and streamed output without gaps.
const textByTask=new Map(run.tasks.map(t=>[t.id,'']));let source=new EventSource(`/api/runs/${id}/events`);eventSource=source;
source.addEventListener('delta',e=>{if(currentRun!==id)return;const v=JSON.parse(e.data);const text=(textByTask.get(v.task_id)||'')+v.data.text;textByTask.set(v.task_id,text);const card=[...$('task-results').children].find(c=>c.dataset.task===v.task_id);if(card)card.querySelector('.output').textContent=text;});
for(const kind of ['tool_start','tool_result','file_backup','file_restore'])source.addEventListener(kind,e=>{if(currentRun!==id)return;const v=JSON.parse(e.data);const card=[...$('task-results').children].find(c=>c.dataset.task===v.task_id);if(card){const label=kind==='tool_start'?`调用 ${v.data.name}：${JSON.stringify(v.data.arguments)}`:kind==='file_backup'?`已保存原文件：${v.data.path}`:kind==='file_restore'?`已恢复文件：${v.data.path}`:`${v.data.name} → ${JSON.stringify(v.data.result)}`;card.querySelector('.tool-log').append(node('div',label));}});
source.addEventListener('status',async e=>{if(currentRun!==id)return;const v=JSON.parse(e.data);const card=[...$('task-results').children].find(c=>c.dataset.task===v.task_id);if(card){card.querySelector('.pill').className=`pill ${v.data.status}`;card.querySelector('.pill').textContent=labels[v.data.status]||v.data.status;card.querySelector('.task-error').textContent=v.data.error||'';}
// Fetch terminal state once; retain the stream so other members continue updating.
if(!['queued','running'].includes(v.data.status)){try{const latest=await api(`/runs/${id}`);if(currentRun!==id)return;for(const t of latest.tasks){const old=[...$('task-results').children].find(c=>c.dataset.task===t.id);if(old&&t.id===v.task_id){const fresh=renderTask(t);fresh.querySelector('.tool-log').replaceWith(old.querySelector('.tool-log'));old.replaceWith(fresh);}}}catch(e){notice(e.message,true);}}});await history();}
$('refresh-run').onclick=()=>action($('refresh-run'),()=>openRun(currentRun));
function renderRoute(route){const card=node('div',undefined,'card');card.dataset.route=route.id;const head=node('div',undefined,'route-header');head.append(node('h2',route.name),node('span',keyState[route.id]?'● Key 已配置':'○ 待配置 Key','key-state'));const grid=node('div',undefined,'route-grid');const fields={};for(const [label,key,type]of [['路由 ID','id','text'],['显示名称','name','text'],['API 根地址（含 /v1）','base_url','url'],['模型 ID','model','text'],['输出上限','max_tokens','number'],['此 Key 的并发上限','parallel_limit','number']]){const [l,i]=field(label,route[key],type);fields[key]=i;grid.append(l);}fields.id.readOnly=!!config.routes.find(r=>r.id===route.id);const [kl,ki]=field('Key（留空沿用已保存的值）','','password');ki.autocomplete='new-password';grid.append(kl);const [el,ei]=field('环境变量（可选，优先于已保存 Key）',route.key_env||'');grid.append(el);card.getValue=()=>({...route,id:fields.id.value.trim(),name:fields.name.value.trim(),base_url:fields.base_url.value.trim().replace(/\/$/,''),model:fields.model.value.trim(),max_tokens:Number(fields.max_tokens.value),parallel_limit:Number(fields.parallel_limit.value),key_env:ei.value.trim()||null});card.getKey=()=>ki.value.trim();const actions=node('div',undefined,'route-actions');const discover=node('button','获取模型','secondary'),check=node('button','连通测试','secondary'),remove=node('button','移除','secondary');remove.onclick=()=>card.remove();const log=node('div','','route-log');discover.onclick=()=>action(discover,async()=>{const r=await api(`/routes/${route.id}/models`);log.textContent='可用模型：'+r.models.join('、');});check.onclick=()=>action(check,async()=>{const r=await api(`/routes/${route.id}/check`,{});log.textContent=`${r.ok?'✓ 通过':'返回值异常'} · ${r.model} · ${r.elapsed_ms} ms · 回答 ${r.answer}`;});actions.append(discover,check,remove,node('small','更改后先保存，再获取模型或测试。'));card.append(head,grid,actions,log);$('routes').append(card);}
function renderSettings(){$('workspace').value=prettyPath(config.workspace);$('concurrency').value=config.max_concurrency;$('workspace-label').textContent='项目 · '+prettyPath(config.workspace);$('routes').replaceChildren();config.routes.forEach(renderRoute);if(config.newapi){$('account-url').value=config.newapi.base_url;$('account-id').value=config.newapi.user_id;$('account-unit').value=config.newapi.quota_per_unit;}}
$('add-route').onclick=()=>renderRoute({id:`peach-key-${Date.now().toString(36)}`,name:'🍑 新路由',base_url:'https://xpeach.codes/v1',model:'gpt-6-astra',max_tokens:4096,parallel_limit:1,key_env:null});
$('save-settings').onclick=()=>action($('save-settings'),async()=>{const cards=[...$('routes').children];const settings={...config,workspace:$('workspace').value,max_concurrency:Number($('concurrency').value),routes:cards.map(c=>c.getValue())};const keys=Object.fromEntries(cards.filter(c=>c.getKey()).map(c=>[c.getValue().id,c.getKey()]));await api('/settings',{settings,keys},'PUT');await loadSettings();notice('设置已保存；Key 使用当前 Windows 账号加密存储。');});
function showBalance(r){$('balance-value').textContent=Number(r.balance).toLocaleString('zh-CN',{maximumFractionDigits:4});$('balance-detail').textContent=`${r.display_name||r.username||'已绑定账号'} · ${r.group||'默认分组'}\n已用额度 ${r.used??'—'} · ${new Date(r.checked_at*1000).toLocaleString('zh-CN')}`;}
$('account-form').onsubmit=e=>{e.preventDefault();const b=e.submitter;action(b,async()=>{const r=await api('/newapi',{account:{base_url:$('account-url').value.replace(/\/$/,''),user_id:$('account-id').value,quota_per_unit:Number($('account-unit').value)},token:$('account-token').value||null},'PUT');$('account-token').value='';showBalance(r);await loadSettings();notice('账号绑定成功。');});};
$('refresh-balance').onclick=()=>action($('refresh-balance'),async()=>showBalance(await api('/newapi/balance')));
async function loadSettings(){const s=await api('/settings');config=s.settings;keyState=s.keys;renderSettings();renderChatRoutes();for(const select of document.querySelectorAll('.member .route')){const previous=select.value;select.replaceChildren();for(const r of config.routes){const o=node('option',`${r.name} · ${r.model}${keyState[r.id]?'':'（未配置 Key）'}`);o.value=r.id;select.append(o);}if(config.routes.some(r=>r.id===previous))select.value=previous;}}
(async()=>{try{const boot=await api('/bootstrap');token=boot.token;await loadSettings();addMember();await history();}catch(e){notice(e.message,true);}})();


function prettyPath(value){return value.startsWith("\\\\?\\")?value.slice(4):value;}
